/** Declaration file generated by dts-gen */

export function generate(config: any): any;

export function id(): any;

export function randomBoolean(value: any): any;

export function randomEmail(): any;

export function randomFruit(): any;

export function randomInteger(min: any, max: any): any;

export function randomName(): any;

export namespace generate {
    const prototype: {
    };

}

export namespace id {
    const prototype: {
    };

}

export namespace randomBoolean {
    const prototype: {
    };

}

export namespace randomEmail {
    const prototype: {
    };

}

export namespace randomFruit {
    const prototype: {
    };

}

export namespace randomInteger {
    const prototype: {
    };

}

export namespace randomName {
    const prototype: {
    };

}

